# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='owner_id',
            field=models.CharField(default=b'NONE', max_length=100),
        ),
    ]
